name: FluidAttacks Pipeline
on: [push, pull_request]

jobs:
  SAST:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
         - uses: docker://docker.io/fluidattacks/sast:latest
           name: SAST_Fluidattacks
           with:
             args: sast scan .
